export const currencies = [
    {
        id: 1,
        currency: 'Bitcoin',
        marketSymbol: 'btcinr',
        img: 'Crypto cards/Bitcoin.svg',
        symbol: 'BTC',
    },
    {
        id: 2,
        currency: 'Ethereum',
        marketSymbol: 'ethinr',
        img: 'Crypto cards/Ethereum.svg',
        symbol: 'ETH',
    },
    {
        id: 3,
        currency: 'Tether',
        marketSymbol: 'usdtinr',
        img: 'Crypto cards/Tether.svg',
        symbol: 'USDT',
    },
    {
        id: 4,
        currency: 'BNB',
        marketSymbol: 'bnbinr',
        img: 'Crypto cards/BNB.svg',
        symbol: 'BNB',
    },
    {
        id: 5,
        currency: 'Solana',
        marketSymbol: 'solinr',
        img: 'Crypto cards/Solana.svg',
        symbol: 'SOL',
    },
    {
        id: 6,
        currency: 'USD Coin',
        marketSymbol: 'usdcinr',
        img: 'Crypto cards/USD Coin.svg',
        symbol: 'USDC',
    },
    {
        id: 7,
        currency: 'Cardano (ADA)',
        marketSymbol: 'adainr',
        img: 'Crypto cards/Cardano (ADA).svg',
        symbol: 'ADA',
    },
    {
        id: 8,
        currency: 'XRP',
        marketSymbol: 'xrpinr',
        img: 'Crypto cards/XRP.svg',
        symbol: 'XRP',
    },
    {
        id: 9,
        currency: 'Terra',
        marketSymbol: 'lunainr',
        img: 'Crypto cards/Terra.svg',
        symbol: 'LUNA',
    },
    {
        id: 10,
        currency: 'Polkadot',
        marketSymbol: 'dotinr',
        img: 'Crypto cards/Polkadot.svg',
        symbol: 'DOT',
    },
    {
        id: 11,
        currency: 'Cardano (AVAX)',
        marketSymbol: 'avaxinr',
        img: 'Crypto cards/Cardano (AVAX).svg',
        symbol: 'AVAX',
    },
    {
        id: 12,
        currency: 'Dogecoin',
        marketSymbol: 'dogeinr',
        img: 'Crypto cards/DogeCoin.svg',
        symbol: 'DOGE',
    },
    {
        id: 13,
        currency: 'Shiba Inu',
        marketSymbol: 'shibinr',
        img: 'Crypto cards/Shiba Inu.svg',
        symbol: 'SHIB',
    },
    {
        id: 14,
        currency: 'Polygon',
        marketSymbol: 'maticinr',
        img: 'Crypto cards/Polygon.svg',
        symbol: 'MATIC',
    },
    {
        id: 15,
        currency: 'Binance USD',
        marketSymbol: 'busdinr',
        img: 'Crypto cards/Binance USD.svg',
        symbol: 'BUSD',
    },
];