export const currencies = [
    {
        id: 1,
        currency: 'Bitcoin',
        marketSymbol: 'btcinr',
        img: 'gift-card.png',
        symbol: 'BTC',
    },
    {
        id: 2,
        currency: 'Ethereum',
        marketSymbol: 'ethinr',
        img: 'gift-card.png',
        symbol: 'ETH',
    },
    {
        id: 3,
        currency: 'Tether',
        marketSymbol: 'usdtinr',
        img: 'gift-card.png',
        symbol: 'USDT',
    },
    {
        id: 4,
        currency: 'BNB',
        marketSymbol: 'bnbinr',
        img: 'gift-card1.png',
        symbol: 'BNB',
    },
    {
        id: 5,
        currency: 'Solana',
        marketSymbol: 'solinr',
        img: 'gift-card.png',
        symbol: 'SOL',
    },
    {
        id: 6,
        currency: 'USD Coin',
        marketSymbol: 'usdcinr',
        img: 'gift-card.png',
        symbol: 'USDC',
    },
    {
        id: 7,
        currency: 'Cardano',
        marketSymbol: 'adainr',
        img: 'gift-card1.png',
        symbol: 'ADA',
    },
    {
        id: 8,
        currency: 'XRP',
        marketSymbol: 'xrpinr',
        img: 'gift-card.png',
        symbol: 'XRP',
    },
    {
        id: 9,
        currency: 'Terra',
        marketSymbol: 'lunainr',
        img: 'gift-card.png',
        symbol: 'LUNA',
    },
    {
        id: 10,
        currency: 'Polkadot',
        marketSymbol: 'dotinr',
        img: 'gift-card1.png',
        symbol: 'DOT',
    },
    {
        id: 11,
        currency: 'Cardano',
        marketSymbol: 'avaxinr',
        img: 'gift-card1.png',
        symbol: 'AVAX',
    },
    {
        id: 12,
        currency: 'Dogecoin',
        marketSymbol: 'dogeinr',
        img: 'gift-card.png',
        symbol: 'DOGE',
    },
    {
        id: 13,
        currency: 'Shiba Inu',
        marketSymbol: 'shibinr',
        img: 'gift-card.png',
        symbol: 'SHIB',
    },
    {
        id: 14,
        currency: 'Polygon',
        marketSymbol: 'maticinr',
        img: 'gift-card1.png',
        symbol: 'MATIC',
    },
    {
        id: 15,
        currency: 'Binance USD',
        marketSymbol: 'busdinr',
        img: 'gift-card.png',
        symbol: 'BUSD',
    },
];